// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Appointment.cs" company="Microsoft">
//     Copyright © Microsoft, 2016
// </copyright>
// <summary>
//     The class.
// </summary>
// <auto-generated />
//  -------------------------------------------------------------------------------------------------------------------

namespace HealthCare.Web.Models
{
  using System;

  /// <summary>
  /// Appointment
  /// </summary>s
  public class Appointment
  {
    /// <summary>
    /// Gets or sets the full name.
    /// </summary>
    /// <value>
    /// The full name.
    /// </value>
    public string FullName { get; set; }

    /// <summary>
    /// Gets or sets the date.
    /// </summary>
    /// <value>
    /// The date.
    /// </value>
    public DateTime Date { get; set; }

    /// <summary>
    /// Gets or sets the email.
    /// </summary>
    /// <value>
    /// The email.
    /// </value>
    public string Email { get; set; }

    /// <summary>
    /// Gets or sets the questionnaire.
    /// </summary>
    /// <value>
    /// The questionnaire.
    /// </value>
    public string Questionnaire { get; set; }

    /// <summary>
    /// Gets or sets the time slot.
    /// </summary>
    /// <value>
    /// The time slot.
    /// </value>
    public string TimeSlot { get; set; }

    /// <summary>
    /// Gets or sets the name of the doctor.
    /// </summary>
    /// <value>
    /// The name of the doctor.
    /// </value>
    public string DoctorName { get; set; }

    /// <summary>
    /// Gets or sets the item identifier.
    /// </summary>
    /// <value>
    /// The item identifier.
    /// </value>
    public int ItemId { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this instance is doctor.
    /// </summary>
    /// <value>
    ///   <c>true</c> if this instance is doctor; otherwise, <c>false</c>.
    /// </value>
    public bool IsDoctor { get; set; }
  }
}