// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SkypeMeeting.cs" company="Microsoft">
//     Copyright © Microsoft, 2016
// </copyright>
// <summary>
//     The class.
// </summary>
// <auto-generated />
//  -------------------------------------------------------------------------------------------------------------------

namespace HealthCare.Web.Models
{
  using System;

  /// <summary>
  /// Skype Meeting
  /// </summary>
  public class SkypeMeeting
  {
    /// <summary>
    /// Gets or sets the meeting identifier.
    /// </summary>
    /// <value>
    /// The meeting identifier.
    /// </value>
    public string MeetingId { get; set; }

    /// <summary>
    /// Gets or sets the display name.
    /// </summary>
    /// <value>
    /// The display name.
    /// </value>
    public string DisplayName { get; set; }

    /// <summary>
    /// Gets or sets the name of the patient.
    /// </summary>
    /// <value>
    /// The name of the patient.
    /// </value>
    public bool IsPatient { get; set; }

    /// <summary>
    /// Gets or sets the item identifier.
    /// </summary>
    /// <value>
    /// The item identifier.
    /// </value>
    public string ItemId { get; set; }

    /// <summary>
    /// Gets or sets the type of the user.
    /// </summary>
    /// <value>
    /// The type of the user.
    /// </value>
    public string UserType { get; set; }

    /// <summary>
    /// Gets or sets the start time.
    /// </summary>
    /// <value>
    /// The start time.
    /// </value>
    public DateTime StartTime { get; set; }

    /// <summary>
    /// Gets or sets the custom identifier.
    /// </summary>
    /// <value>
    /// The custom identifier.
    /// </value>
    public string CustomId { get; set; }

    /// <summary>
    /// Gets or sets the emr identifier.
    /// </summary>
    /// <value>
    /// The emr identifier.
    /// </value>
    public string EmrId { get; set; }

    /// <summary>
    /// Gets or sets the URL.
    /// </summary>
    /// <value>
    /// The URL.
    /// </value>
    public string Url { get; set; }

    /// <summary>
    /// Gets or sets the skype client.
    /// </summary>
    /// <value>
    /// The skype client.
    /// </value>
    public bool IsSkypeClient { get; set; }
  }
}