// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TrustedApiOptions.cs" company="Microsoft">
//     Copyright © Microsoft, 2016
// </copyright>
// <summary>
//     The class.
// </summary>
// <auto-generated />
//  -------------------------------------------------------------------------------------------------------------------

namespace HealthCare.Web.Models
{
  public class TrustedApiOptions
  {
    /// <summary>
    /// Gets or sets the allowed origins.
    /// </summary>
    /// <value>
    /// The allowed origins.
    /// </value>
    public string AllowedOrigins { get; set; }

    /// <summary>
    /// Gets or sets the meeting URL.
    /// </summary>
    /// <value>
    /// The meeting URL.
    /// </value>
    public string MeetingUrl { get; set; }

    /// <summary>
    /// Gets or sets the application session identifier.
    /// </summary>
    /// <value>
    /// The application session identifier.
    /// </value>
    public string ApplicationSessionId { get; set; }
  }
}