// --------------------------------------------------------------------------------------------------------------------
// <copyright file="KeyVaultHelper.cs" company="Microsoft">
//     Copyright © Microsoft, 2016
// </copyright>
// <summary>
//     The class.
// </summary>
// <auto-generated />
//  -------------------------------------------------------------------------------------------------------------------

namespace HealthCare.Web.HelperClasses
{
    /// <summary>
    /// This helper class provides store for key vault secrets
    /// </summary>
    public static class KeyVaultHelper
    {
        /// <summary>
        /// Gets or sets the SPO Password.
        /// </summary>
        /// <value>
        /// The encrypt secret.
        /// </value>
        public static string SpoPassword { get; set; }

        /// <summary>
        /// Gets or sets the encryption key.
        /// </summary>
        /// <value>
        /// The encryption key.
        /// </value>
        public static string EncryptionKey { get; set; }

        /// <summary>
        /// Gets or sets the encryption salt.
        /// </summary>
        /// <value>
        /// The encryption salt.
        /// </value>
        public static string EncryptionSalt { get; set; }
    }
}